name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    branches:
      - main
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Exécuter uniquement si CI réussi

    steps:
    - name: Pull Docker image
      run: sudo docker pull yp522/backend_lfm:latest
    
    - name: Delete Old docker container
      run: sudo docker rm -f backend_lfm-container || true
    
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name backend_lfm-container yp522/backend_lfm
