name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: "localhost"
      DB_PORT: "5432"

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run tests (Jest)
      run: npm run test

  build-and-push:
    needs: test  # ✅ Bloque le build Docker si les tests échouent
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build -t yp522/backend_lfm .

    - name: Push to DockerHub
      run: docker push yp522/backend_lfm:latest
