name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
    - uses: actions/checkout@v3

    - name: Debug Environment Variables
      run: |
        echo "DB_NAME: $DB_NAME"
        echo "DB_USER: $DB_USER"
        echo "DB_PASSWORD: ${DB_PASSWORD:0:2}****${DB_PASSWORD: -2}"
        echo "DB_HOST: $DB_HOST"
        echo "DB_PORT: $DB_PORT"

    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build -t yp522/backend_lfm .

    - name: Push to DockerHub
      run: docker push yp522/backend_lfm:latest
